% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
  \setmainfont[]{Open Sans}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{pdfpages}
\usepackage[default]{open sans}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{sidecap}
\usepackage[spanish]{babel}
\pagestyle{fancy}
\renewcommand{\headrulewidth}{0pt}
\fancyhead{}
\setlength{\headheight}{23pt}
\lhead{\includegraphics[width=7cm,height=140cm]{"./logos/logo_oecc.pdf"}}
\fancyfoot{}
\lfoot{\includegraphics[width=5.0cm,height=140cm]{"./logos/muni.jpg"}}
\rfoot{\thepage}
\definecolor{graycustom}{HTML}{7b7b7e}
\usepackage{floatrow}
\floatsetup[figure]{capposition=bottom}
\renewcommand{\arraystretch}{1.5}
\usepackage{svg}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\author{}
\date{\vspace{-2.5em}}

\addto\captionsspanish{\renewcommand{\figurename}{Gráfico}}
\usepackage[labelsep=endash]{caption}
\begin{document}


\textcolor{graycustom}{\Large Consideraciones metodológicas} \newline

El Observatorio Económico de la Municipalidad de Corrientes lleva a cabo
diversos informes socio-demográficos, utilizando como fuente principal
la base de microdatos de la Encuesta Permanente de Hogares elaborada por
el Instituto Nacional de Estadísticas y Censos (INDEC) y presentada con
una periodicidad trimestral. La misma se realiza a través de
cuestionarios presenciales que luego son volcados a bases de datos para
ser utilizados por el público en general.

A raíz del decreto N.º 297/2020 que establece el aislamiento social,
preventivo y obligatorio por la pandemia causada por el virus SARS-COV2,
y con el objetivo de no interrumpir el operativo continuo, el INDEC pasó
de la modalidad presencial a la telefónica para contactar y realizar la
entrevista a los hogares.

Esto implica que, a partir del Cuarto trimestre del 2020, el
relevamiento habitual de la EPH se ha visto afectado no solo por el
cambio de modalidad de entrevista, sino también por la cobertura de la
muestra, ya que la misma se redujo a las viviendas que tenían un número
de teléfono conocido o cuyo número se pudo obtener mediante estrategias
que no implicaban contacto personal. Ambos aspectos impactan en la
cantidad de hogares sin respuesta y ocasionan sesgos en las
estimaciones.

Gracias a los esfuerzos del INDEC para asegurar la difusión de las
estadísticas y aminorar los posibles sesgos producidos en los datos del
trimestre, el Observatorio Económico pudo llevar a cabo este informe.
Sin embargo, creemos oportuno realizar las aclaraciones metodológicas
antes descritas.

Por último, este trabajo se ha hecho considerando a los datos del cuarto
trimestre de 2021, con excepción de los apartados de informalidad por
sectores y calificación laboral por sectores, que se hicieron trabajando
en conjunto con las bases del tercer trimestre del 2021.

\newpage

\textcolor{graycustom}{\Large Mercado de trabajo: 
Tasas e indicadores socioeconómicos (EPH)} \newline

Según las proyecciones de INDEC basadas en el último Censo de población,
la cantidad de habitantes total de la ciudad en el año 2021 es de 414927
personas. De ese total el 48.83\% son hombres y el restante 51.17\%,
mujeres.

De acuerdo con los datos publicados por el INDEC, basados también en el
último Censo Nacional de Población, Hogares y Viviendas (2010), la
población por edades se compone de la siguiente manera:

\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-6-1.pdf}
\caption{}
\end{figure}


\begin{table}[htb]

\caption{\label{tab:unnamed-chunk-5}Composición de la población}
\centering
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{18em}>{\raggedleft\arraybackslash}p{14em}>{\raggedleft\arraybackslash}p{14em}}
\toprule
\begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Edad}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Hombres}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Mujeres}}}\endgroup\\
\midrule
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{0-14}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{28.00\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{25.00\%}}\\
15-24 & 21.00\% & 20.00\%\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{25-34}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{16.00\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{16.00\%}}\\
35-44 & 11.00\% & 12.00\%\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{45-59}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{15.00\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{15.00\%}}\\
\addlinespace
Mayor o igual a 60 & 9.00\% & 12.00\%\\
\bottomrule
\end{tabular}
\end{table}

\pagebreak

\newpage

\textcolor{graycustom}{\Large Indicadores de participación laboral}
\newline

Los resultados del cuarto trimestre de 2021 para la Ciudad de Corrientes
muestran que la tasa de actividad es del 43.53\%.

Del total de personas que conforman la PEA, el 56.99\% son hombres y el
43.01\% mujeres. Por otro lado, se observa que del total de mujeres, el
35.93\% forman parte de la PEA, mientras que en el caso de los hombres
el porcentaje que forma parte de la PEA alcanza el 51.78\%.

La población económicamente activa (PEA), a su vez, está compuesta por
los ocupados y desocupados. Este último grupo presiona activamente sobre
el mercado laboral en búsqueda de una ocupación.

La definición vista de PEA, no incluye al trabajo no remunerado
(doméstico, voluntario y de subsistencia). Esto implica que, en la
medición de la actividad de la EPH, no se considera activa a la
población que realiza producción o tratamiento de bienes exclusivamente
para autoconsumo. Esto trae inconvenientes en cuanto a la subestimación
de la participación femenina en la actividad económica. Por la
importancia que tiene este tópico en las brechas de género, el tema es
tratado especialmente en el ``Informe de Género'' realizado por el
Observatorio Económico de la Ciudad de Corrientes.

A continuación, se aprecian los porcentajes, tanto de hombres como de
mujeres, que forman parte de la PEA, desagregados por rangos de edad.

\begin{table}[htb]

\caption{\label{tab:unnamed-chunk-11}Participación laboral por sexo y edad}
\centering
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{18em}>{\raggedleft\arraybackslash}p{14em}>{\raggedleft\arraybackslash}p{14em}}
\toprule
\begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Edad}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Hombres}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Mujeres}}}\endgroup\\
\midrule
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{15-24 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{32.89\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{16.83\%}}\\
25-34 años & 87.61\% & 54.22\%\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{35-44 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{95.21\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{74.23\%}}\\
45-59 años & 91.05\% & 66.52\%\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{Igual o mayor a 60 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{40.14\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{17.02\%}}\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-12-1.pdf}
\caption{}
\end{figure}

Se puede observar que, para todos los rangos etarios existe una brecha
en la tasa de actividad que muestra que hay menos mujeres participando
en el mercado laboral, en comparación a los hombres.

A modo de observación, para ambos sexos, el porcentaje máximo de
participación se encuentra entre los 35 a 44 años.

\newpage
Tanto en la tabla como en el Gráfico 3 se exponen los porcentajes tanto
de hombres como de mujeres pertenecientes a la PEA, desagregados por el
nivel de educación alcanzado, junto con las respectivas brechas. Se
entiende como brecha a la diferencia entre el porcentaje de hombres y
mujeres que conforman la PEA para cada nivel educativo.

\begin{table}[htb]

\caption{\label{tab:unnamed-chunk-14}Participación laboral por sexo y nivel educativo}
\centering
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{12em}>{\raggedleft\arraybackslash}p{10em}>{\raggedleft\arraybackslash}p{10em}>{\raggedleft\arraybackslash}p{10em}}
\toprule
\begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Nivel}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Hombres}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Mujeres}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Brecha}}}\endgroup\\
\midrule
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{Primaria Completa}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{48.81\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{25.25\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{27.23\%}}\\
Secundaria Completa & 73.53\% & 44.51\% & 9.64\%\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{Superior Completo}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{87.60\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{77.31\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{9.98\%}}\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-15-1.pdf}
\caption{}
\end{figure}

\newpage

Nuevamente, hay una brecha positiva en la participación para todos los
niveles, siendo la mas importante para personas con primario completo,
para el que la brecha llega a 27.23\% y para el resto cae a niveles
cercanos al 9\%.

Los valores que se presentan y grafican a continuación corresponden al
promedio de horas semanales que trabajan tanto hombres como mujeres,
desagregados por edad.

\begin{table}[htb]

\caption{\label{tab:unnamed-chunk-18}Carga laboral semanal por sexo y edad}
\centering
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{12em}>{\raggedleft\arraybackslash}p{10em}>{\raggedleft\arraybackslash}p{10em}>{\raggedleft\arraybackslash}p{10em}}
\toprule
\begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Edad}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Hombres}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Mujeres}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Brecha}}}\endgroup\\
\midrule
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{15-24 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{69.56}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{47.16}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{22.40}}\\
25-34 años & 75.66 & 69.09 & 6.57\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{35-44 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{82.84}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{58.99}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{23.85}}\\
45-59 años & 80.32 & 70.35 & 9.97\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{Igual o mayor a 60 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{71.70}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{57.85}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{13.85}}\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-19-1.pdf}
\caption{}
\end{figure}

\newpage

Se observa que para todos los rangos etarios los hombres tienen una
carga laboral superior a las mujeres, dándose las brechas más grandes
para las personas de 35 a 44 años.

\newpage

Por último, la tasa de empleo en la Ciudad de Corrientes para el
trimestre en cuestión asciende 42.64\%, esta tasa se calcula como el
cociente entre el total de ocupados y la población total de referencia.
Por su parte, la tasa de desocupación, que se calcula como el cociente
entre desocupados y la Población Económicamente Activa (PEA), es del
2.04\%.

\begin{figure}[hbp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-22-1.pdf}
\caption{}
\end{figure}

\newpage

\textcolor{graycustom}{\Large Empleo público y privado} \newline

Del total de empleados de la ciudad, el porcentaje de empleados públicos
es de 24.22\% siendo 75.78\% trabajadores pertenecientes al sector
privado.

\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-24-1.pdf}
\caption{}
\end{figure}

En el sector público, el promedio de edad de los trabajadores es de 45
años, mientras que en el sector privado es de 39, trabajando 35 y 38
horas semanales en promedio en el sector público y privado,
respectivamente. A su vez, el Estado cuenta con una calificación laboral
del 57.57\%, mientras que el sector privado, tan solo del 19.78\%.

Por otro lado, el sector público se compone de una participación de
58.53\% mujeres y 41.47\% hombres. Mientras que, en el sector privado,
el porcentaje de hombres llega al 62.13\%.


\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-30-1.pdf}
\caption{}
\end{figure}

\newpage
En términos de la composición por sectores en el empleo público (Gráfico
8), la ``Administración Pública'' cuenta con la mayor participación
laboral, ocupando un 56.07\% del total de empleos públicos, seguida por
la ``Enseñanza'' en todos sus niveles, con un 31.34\% del total de
empleos y en tercer lugar el rubro de la ``Salud'', con un 10.01\% de la
participación.

\begin{figure}[htbp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-32-1.pdf}
\caption{}
\end{figure}

\newpage \textcolor{graycustom}{\Large Tasas de informalidad laboral}

Para el análisis del trabajo no registrado, se construye una tasa de
informalidad que relaciona la cantidad de personas que poseen un empleo
en relación de dependencia, pero no perciben aportes jubilatorios por el
mismo. En la tabla y el gráfico siguiente se presenta información
relacionada a la población que trabaja de manera informal desagregada
tanto por edad como por sexo:

\begin{table}[htb]

\caption{\label{tab:unnamed-chunk-36}Informalidad laboral por sexo y edad}
\centering
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{18em}>{\raggedleft\arraybackslash}p{14em}>{\raggedleft\arraybackslash}p{14em}}

\begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Edad}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Hombres}}}\endgroup & \begingroup\fontsize{12}{14}\selectfont \cellcolor[HTML]{29aee4}{\textcolor{white}{\textbf{Mujeres}}}\endgroup\\
\midrule
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{15-24 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{94.62\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{100.00\%}}\\
25-34 años & 53.86\% & 51.17\%\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{35-44 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{36.54\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{43.80\%}}\\
45-59 años & 25.05\% & 22.92\%\\
\cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{+60 años}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{28.06\%}} & \cellcolor[HTML]{F0FFFF}{\cellcolor{gray!6}{23.45\%}}\\

\end{tabular}
\end{table}


\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-37-1.pdf}
\caption{}
\end{figure}

\newpage
Al analizar la informalidad laboral por sector de actividad, los menores
valores se encuentran en el sector de enseñanza (7.04\%); suministro de
Agua, alcantarillado, gestión de desechos y actividades de saneamiento
(16.00\%); el sector de administración pública y defensa, planes de
seguro social obligatorio (18.58\%); agricultura, ganadería,
silvicultura, caza y pesca (29.71\%) y transporte y almacenamiento
(31.04\%). Por otro lado, los valores más altos están en el sector de
actividades inmobiliarias; construcción; servicio doméstico y
actividades para consumo propio; otras actividades de servicio; y
actividades administrativas y servicios de apoyo.

\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-39-1.pdf}
\caption{}
\end{figure}


\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-40-1.pdf}
\caption{}
\end{figure}

\newpage

\textcolor{graycustom}{\Large Tasas de calificación laboral} \newline

En la EPH se clasifica a los empleados en cuatro categorías:
profesionales, técnicos, operarios y trabajadores no calificados. A
efectos de este análisis se consideran calificados a los profesionales o
técnicos, mientras que a los no calificados se le suman los operarios
para determinar la categoría final de no calificados.

Del total de la población de la ciudad, solo el 28.72\% son calificados,
mientras que el 71.28\% restante son no calificados. Del total de los
hombres, el 25.03\% son calificados, mientras que del total de las
mujeres el porcentaje de calificación es del 34.00\%.

Al analizar la calificación laboral por sector de actividad los valores
más altos están en los rubros de información y comunicación (92.74\%);
enseñanza (84.94\%); profesionales, científicos y técnicos (84.25\%);
salud humana y servicios sociales(60.98\%); y actividades inmobiliarias
(59.45\%).

\begin{figure}[htp]
\includegraphics{Informe-Mercado-Laboral_files/figure-latex/unnamed-chunk-44-1.pdf}
\caption{}
\end{figure}

\end{document}
