---
title: "R Notebook"
output: html_notebook
---
```{r}
setwd("~/GitHub/informegenero")
library(eph)
library(tidyverse)
library(formattable)
ephi<- get_microdata(year=2020, trimester = 2, type = "individual")
ephh<- get_microdata(year=2020, trimester = 2, type = "hogar")

eph2t<- left_join(ephi, ephh)
```
# Ingreso promedio según categoría ocupacional y participación laboral de hombres y mujeres.
```{r}
ephcorr<- eph2t %>% filter(AGLOMERADO==12 & ESTADO!=0 & P21!=-9) %>% mutate( PP04B_COD=as.character(PP04B_COD),
                          PP04B_COD=case_when(nchar(PP04B_COD)==4~PP04B_COD,
                                              nchar(PP04B_COD)==1~ paste0("0",PP04B_COD,"00"),
                                              nchar(PP04B_COD)==2~ paste0(PP04B_COD,"00"),
                                              nchar(PP04B_COD)==3~ paste0("0",PP04B_COD)),
                          SECTOR= substr(PP04B_COD,1,2),
                          SEXO= case_when(CH04==1~ "Hombres",
                                          CH04==2 ~ "Mujeres"))

caes<- read.csv("SECTORESCAES.csv", sep = ";", colClasses = "character")
eph2t<- left_join(eph2t,caes)

```

```{r}
porsectores<- ephcorr %>% group_by(SECTOR_ACT) %>% summarise(total=sum(PONDERA), "Ingreso promedio"=weighted.mean(P21,PONDIIO), "Total Mujeres"=sum(PONDERA[SEXO=="Mujeres"]), "Total de Hombres"=sum(PONDERA[SEXO=="Hombres"]), "Ingreso promedio Mujeres"=case_when(!is.na(weighted.mean(P21[SEXO=="Mujeres"],PONDIIO[SEXO=="Mujeres"]))~weighted.mean(P21[SEXO=="Mujeres"],PONDIIO[SEXO=="Mujeres"]),is.na(weighted.mean(P21[SEXO=="Mujeres"],PONDIIO[SEXO=="Mujeres"]))~0), "Ingreso promedio Hombres"=case_when(!is.na(weighted.mean(P21[SEXO=="Hombres"],PONDIIO[SEXO=="Hombres"]))~weighted.mean(P21[SEXO=="Hombres"],PONDIIO[SEXO=="Hombres"]),is.na(weighted.mean(P21[SEXO=="Hombres"],PONDIIO[SEXO=="Hombres"]))~0))

porsectores<- porsectores %>% mutate("Brecha de ingreso"=percent((`Ingreso promedio Hombres`-`Ingreso promedio Mujeres`)/`Ingreso promedio Hombres`), "Tasa de feminización"=percent(`Total Mujeres`/(`Total Mujeres`+`Total de Hombres`)))

porsectores <- porsectores %>% filter(!is.na(SECTOR_ACT)) %>% arrange(`Tasa de feminización`)





```

